---
all:
    samplesheet: '/trinity/home/r115502/MINT/WES-snake/samplesheet.csv' # specify sarek samplesheet: must contain patient, sample, status, lane, fastq_1 and fastq_2
    data_dir: "/trinity/home/r115502/MINT/fastq/"  # Specify main data directory
    output_dir: "/trinity/home/r115502/MINT/output/"                  # Specify main output directory   

sarek:
  workdir: '/trinity/home/r115502/MINT/WES-snake/.sarek/work/' # directory to save sarek working dir
  targetregions : "/trinity/home/r115502/Resources/target_regions/S31285117_Regions.bed" # Exome regions
  interval_padding: 100 # region padding around capture regions
  HMF_PON: "/trinity/home/r115502/Resources/PON/hg38/hmf_pon.vcf.gz" # Path to HMF PON for annotation

CopyWriteR:
    cores: 10 # number of cores
    binsizes: ['100kbp','1000kbp'] # CopyWriteR binsize (default=100kbp and 1000kbp)
    cytobands: '/trinity/home/r115502/Resources/cytobands/hg38/cytoBand.txt'

ACE:
    penalty : 0 # Penalty for low purity solutions
    penploidy : 0.5 # penalty for high ploidy solutions

PureCN:
    ref: '/trinity/home/r115502/Resources/BWAIndex/genome.fa' 
