---
all:
    samplesheet: '/trinity/home/r115502/CATNON/WES-snake/samplesheet.csv' # specify sarek samplesheet: must contain patient, sample, status, lane, fastq_1 and fastq_2
    data_dir: "/trinity/home/r115502/CATNON/bam_IDHmt/"  # Specify main data directory
    output_dir: "/trinity/home/r115502/CATNON/output/"                  # Specify main output directory
    ref: '/trinity/home/r115502/Resources/BWAIndex/genome.fa' # Path to reference genome

sarek:
  workdir: '/trinity/home/r115502/CATNON/WES-snake/.sarek/work/' # directory to save sarek working dir
  targetregions : "/trinity/home/r115502/CATNON/targetregions/3112671_Covered.hg38.bed" # target regions
  interval_padding: 100 # region padding around capture regions
  HMF_PON: "/trinity/home/r115502/Resources/PON/hg38/hmf_pon.vcf.gz" # Path to HMF PON for annotation
  COSMIC: "/trinity/home/r115502/Resources/COSMIC/hg38/Cosmic_GenomeScreensMutant_v103_GRCh38_chr.vcf.gz" # Path to COSMIC vcf for annotation

CopyWriteR:
    cores: 1 # number of cores
    binsizes: ['100kbp','1000kbp'] # CopyWriteR binsize (default=100kbp and 1000kbp)
    cytobands: '/trinity/home/r115502/Resources/cytobands/hg38/cytoBand.txt'

ACE:
    penalty : 0 # Penalty for low purity solutions
    penploidy : 0.5 # penalty for high ploidy solutions

CNH:
    path: '/trinity/home/r115502/CATNON/WES-snake/scripts/CNH/' # Path to CNH code
    
PureCN:
    min_af: 0.1 # minimum allele frequency to include for SNV likelihoods
    min_bq: 20 # minimum base quality of variant position
    min_alt: 5 # minimum number of variant supporting reads
    min_cosmic_cnt: 10 # minimum number of cosmic counts of variant to give high somatic prior

CNA_PON:
    100kbp: '/trinity/home/r115502/PON/PON_Heidelberg_panel/output/PON/CNA_PON_100kbp.Rds'
    1000kbp: '/trinity/home/r115502/PON/PON_Heidelberg_panel/output/PON/CNA_PON_1000kbp.Rds'
