executor: slurm
restart-times: 0

jobs: 20
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60

slurm-logdir: "logs/slurm/"
slurm-jobname: 'WES'

use-conda: True
use-singularity: False
rerun-incomplete: True

default-resources:
    mem_mb: 50000
    runtime: 3000
    gpu: 0
