library(QDNAseq)
library(Biobase)
#library(ACE)
library(fields)


#########################################################################/**
# @RdocFunction EstimateErrorAbsoluteProfile
#
# @title "Calculate Error (not normalized) for specific absolute copy number profile"
#
# @synopsis
#
# \description{
#     @get "title".
# }
#
# \arguments{
#     \item{q}{Vector of absolute copy number level, as generated in the function EstimateErrorTissue}
#     \item{segmentdata}{segmentdata$lengths correspond to the absolute copy number level}
# }

EstimateErrorAbsoluteProfile <- function(segmentdata,q){
   return(sum(segmentdata$lengths*abs(q-round(q)) ) )
}

EstimateErrorAbsoluteProfile_SD <- function(segmentdata,q){
   return(sum(segmentdata$lengths*abs(q-round(q))) -sum(segmentdata$lengths*segmentdata$q_sd_segs *sqrt(2/pi)))
}

#########################################################################/**
# @RdocFunction EstimateErrorTissue
#
# @title "Calculate Error (not normalized) for specific absolute copy number profile. This function is called repeatedly with different Purity and Ploidy to find the lowest value"
#
# @synopsis
#
# \description{
#     @get "title".
# }
#
# \arguments{
#     \item{Purity}{Purity of tumor sample, not necessarily the optimal purity}
#     \item{segmentdata}{dataframe as generated by DataFrameToSegmentWeights}
#     \item{Ploidy}{Ploidy of tumor sample, not necessarily the optimal Ploidy}
# }


EstimateErrorTissue <- function(segmentdata,Purity,Ploidy){
#  print(paste("Estimate",Purity,Ploidy))
  a1 = (Purity*Ploidy+ 2*(1-Purity))/Purity
  a2 = -2*(1-Purity)/Purity
  q = a1*segmentdata$values + a2

  return(EstimateErrorAbsoluteProfile(segmentdata,q))
}

EstimateErrorTissue_SD <- function(segmentdata,Purity,Ploidy){
  a1 = (Purity*Ploidy+ 2*(1-Purity))/Purity
  a2 = -2*(1-Purity)/Purity
  q = a1*segmentdata$values + a2
  segmentdata$q_sd_segs = a1*segmentdata$sd_segs 

  return(EstimateErrorAbsoluteProfile_SD(segmentdata,q))
}



Heterogeneity <- function(segmentdata,k){
  return(sum(segmentdata$lengths*abs(segmentdata$values*k - round(segmentdata$values*k))) /sum(segmentdata$lengths))
}

#########################################################################/**
# @RdocFunction EstimateHeterogeneity
#
# @title "Fit heterogeneity. Tries multiple purities and ploidies and returns an error Matrix, called r - sorry for the confusing variable name!"
#
# @synopsis
#
# \description{
#     @get "title".
# }
#
# \arguments{
#     \item{Purity}{Vector of potential Purities for tumor sample}
#     \item{df}{dataframe as generated by DataFrameToSegmentWeights}
#     \item{Ploidy}{Vector of potential Ploidies of tumor sample}
# }


EstimateHeterogeneity <- function(df, Ploidy=seq(1.5,5,0.01), Purity = seq(0.05,1.005,0.01)){
  r=matrix(rep(0,length(Ploidy)*length(Purity)),ncol=length(Ploidy),nrow=length(Purity))

#  print(paste(Purity,Ploidy))
  ind1=1
  ind2=1
  for(ind1 in 1:length(Purity)){
    for(ind2 in 1:length(Ploidy)){
      r[ind1,ind2]=EstimateErrorTissue(df,Purity[ind1],Ploidy[ind2])
    }
  }

# normalize Error matrix outside of the loop as it is faster 

  r = r/sum(df$values,df$lengths);
  return(r)
}

#########################################################################/**
# @RdocFunction ComputeMinimum
#
# @title ""
#
# @synopsis
#
# \description{
#     @get "title".
# }
#
# \arguments{
#     \item{Purity}{Vector of potential Purities for tumor sample}
#     \item{r}{error matrix as generated by EstimateHeterogeneity}
#     \item{Ploidy}{Vector of potential Ploidies of tumor sample}
# }


ComputeMinimum <- function(Ploidy=seq(1.5,5,0.01), Purity = seq(0.05,1.005,0.01),r){
  MinIndr= which(r==min(r))

  MinIndr = MinIndr

  MinPloidy = Ploidy[  floor((MinIndr[1]-1) / nrow(r))+1  ]
  MinPurity = Purity[((MinIndr[1]-1) %% nrow(r))+1]

  mr = min(r)

  MinHeterogeneity = mr[1] 
  return(list(MinHeterogeneity,MinPurity,MinPloidy,r))   
}


#########################################################################/**
# @RdocFunction DataFrameToSegmentWeights
#
# @title "Converts data frame on bin level to data frame on segment level. Format is explained in detail below"
#
# @synopsis
#
# \description{
#     @get "title".
# }
#
# \arguments{
#     \item{df}{dataframe as generated by DataFrameToSegmentWeights}
# }



DataFrameToSegmentWeights <- function(df){
#converts dataframe from format:
#      	chr	start	end	segments
#	1	1	999	0.5
#	1	1000	1999	0.5
#	1	2000	2999	-0.3
#	1	3000	3999	NA
#	1	4000	4999	-0.3
#
#to:
#
#value	length
#0.5	2000
#-0.3	3000
# some effort needs to be done to handle missing data

  dfNoNA = df[!is.na(df$segments),]

  tmp = rle(as.vector(na.exclude(df$segments)))
  cSum = cumsum(tmp$lengths)

  if(length(cSum)>1){
    startCoordinates = c(dfNoNA$start[1],dfNoNA$start[cSum[1:(length(cSum)-1)]+1])
  }
  else{
    startCoordinates=c(dfNoNA$start[1])
  }
  endCoordinates = dfNoNA$end[cSum]
  chrom=dfNoNA$chrom[cSum]

  segmentdata = data.frame(startCoordinates=startCoordinates,endCoordinates=endCoordinates,chrom=chrom,values=tmp$values,lengths=endCoordinates-startCoordinates+1)
  weightedmean = (sum(segmentdata$values*segmentdata$lengths)/sum(segmentdata$lengths))

  if(weightedmean <0.5){
    segmentdata$values = 2^segmentdata$values
     weightedmean = (sum(segmentdata$values*segmentdata$lengths)/sum(segmentdata$lengths))
  }
  segmentdata$values =  segmentdata$values/weightedmean


  return(segmentdata)
}

DataFrameToSegmentWeights_SD <- function(df){
#converts dataframe from format:
#       chr     start   end     segments
#       1       1       999     0.5
#       1       1000    1999    0.5
#       1       2000    2999    -0.3
#       1       3000    3999    NA
#       1       4000    4999    -0.3
#
#to:
#
#value  length
#0.5    2000
#-0.3   3000
# some effort needs to be done to handle missing data

  dfNoNA = df[!is.na(df$segments),]

  tmp = rle(as.vector(na.exclude(df$segments)))
 
  nsegs=length(tmp$lengths)
  sd_segs=rep(0,nsegs)

  cn_bins = df$cn
  seg_bins = df$segments
  cnt=1  
  for(i in 1:nsegs){
 #   print(paste(i,cnt,tmp$lengths[i]))
 #   print(seg_bins[cnt:(cnt+r$lengths[i]-1)])
    sd_segs[i] = sd(cn_bins[1:tmp$lengths[i]]-seg_bins[cnt:(cnt+tmp$lengths[i]-1)])/sqrt(tmp$lengths[i])
    #HetEst = HetEst + sqrt(2/pi)*sd_segs[i]*(tmp$lengths[i]/sum(r$lengths))
    cnt=cnt+tmp$lengths[i]
  }

  cSum = cumsum(tmp$lengths)

  if(length(cSum)>1){
    startCoordinates = c(dfNoNA$start[1],dfNoNA$start[cSum[1:(length(cSum)-1)]+1])
  }
  else{
    startCoordinates=c(dfNoNA$start[1])
  }
  endCoordinates = dfNoNA$end[cSum]
  chrom=dfNoNA$chrom[cSum]

  segmentdata = data.frame(startCoordinates=startCoordinates,endCoordinates=endCoordinates,chrom=chrom,values=tmp$values,lengths=endCoordinates-startCoordinates+1,sd_segss=sd_segs)
  weightedmean = (sum(segmentdata$values*segmentdata$lengths)/sum(segmentdata$lengths))

  if(weightedmean <0.5){
    segmentdata$values = 2^segmentdata$values
     weightedmean = (sum(segmentdata$values*segmentdata$lengths)/sum(segmentdata$lengths))
  }
  segmentdata$values =  segmentdata$values/weightedmean
  segmentdata$sds = 

  return(segmentdata)
}

