########################################################################################################*//

# RdocFuntion plotSample

# @title "plot Sample"

# \arguments{
#     \item{dfRefit}{Dataframe generated by function: DataFrameToSegmentWeights - not rescaled yet}
#     \item{filename}{filename of plot}
#     \item{main}{title of plot}
#     \item{reScale}{Boolean that indicates if the input is relative or absolute} 
#     \item{Purity}{Fitted Cellularity}
#     \item{Ploidy}{Fitted Ploidy}
#     \item{main}{title of plot}
#     \item{Purity}{Cellularity}
#     \item{Heterogeneity}{Indicates heterogeneity index}
#     \item{ChromBorders}{Borders of each chromosome in basepairs}
# }

#*/##########################################################################################################


plotSample <- function(dfRefit,filename,main,reScale,Purity,Ploidy,Heterogeneity,ChromBorders){

  if(reScale==TRUE){
    a1 = (Purity*Ploidy+ 2*(1-Purity))/Purity
    a2 = -2*(1-Purity)/Purity
    q = a1*dfRefit$values + a2
    pdf(filename,width=10,height=6)

    plot(NULL,xlim=c(0,max(dfRefit$absEnd)),ylim=c(0,6),xaxs='i',yaxs='i',xlab='Genome Location',ylab='Absolute Copy Number',xaxt='n',yaxt='n',main=main)
    mtext(paste(
       paste("Purity=",Purity,sep=""),
       paste("Ploidy=",Ploidy,sep=""),
       paste("Heterogeneity=",format(Heterogeneity,digits=2,nsmall=3),sep=""),sep="\n"),side=3,adj=1)
    xax=(ChromBorders$V3+c(0,ChromBorders$V3[-length(ChromBorders$V3)]))/2

    for(i in seq(1,22.5,2)){
      rect(ChromBorders$V3[i],0,ChromBorders$V3[i+1],10,col='#cccccc',border=NA)    
    }

    rect(dfRefit$absStart[1],round(q[1]),dfRefit$absEnd[1],q[1],border=NA,col='#9999ff')
    lines(c(dfRefit$absStart[1],dfRefit$absEnd[1]),rep(q[1],2),col='#0000A0',xlim=c(0,max(dfRefit$absEnd)),ylim=c(0,5),type='l',lwd=2)

    for(i in 1:5){
      abline(h=i,lty=2,col=1)
    }

    for(i in 2: nrow(dfRefit)){
       rect(dfRefit$absStart[i],round(q[i]),dfRefit$absEnd[i],q[i],border=NA,col='#9999ff')
       lines(c(dfRefit$absStart[i],dfRefit$absEnd[i]),rep(q[i],2),lwd=2,col='#0000A0')
    }

    par(ylbias=0.2)

    axis(2,at=0:5,tck=0.022,col=1,lty=1,pos=0,las=2)

    par(ylbias=0.9)

    axis(1,at=xax[seq(1,22.5,2)],labels=seq(1,22.5,2),pos=0,lty=1,col=1,las=0,tck=0.022)
    axis(3,at=NULL,labels=F,tck=0,ann=F)
 
    dev.off()
  }
  else{
    pdf(filename)
    plot(c(dfRefit$absStart[1],dfRefit$absEnd[1]),rep(dfRefit$values[1],2),col=1,xlim=c(0,max(dfRefit$absEnd)),ylim=c(0,8),type='l',lwd=2,main=main)
    for(i in 2: nrow(dfRefit)){lines(c(dfRefit$absStart[i],dfRefit$absEnd[i]),rep(dfRefit$values[i],2),lwd=2)}
    dev.off()
  }
}

########################################################################################################*//

# RdocFuntion plotErrors

# @title "plot heatmap of errors, or line graph in case the Purity is fixed (cell lines)"

# \arguments{
#     \item{r}{Error matrix}
#     \item{filename}{filename of plot}
#     \item{Title}{title of plot}
#     \item{Purity}{Fitted Cellularity}
#     \item{Ploidy}{Fitted Ploidy}
# }

#*/##########################################################################################################



plotError <- function(r,Ploidy,Purity,filename,Title){

  if(length(Purity)>1){
    pdf(filename)
    image.plot(x=Purity,y=Ploidy,z=r,xlab="Purity",ylab="Ploidy",main=Title)
    dev.off()
  }else{
    pdf(filename)
    plot(Ploidy,r[1,],xlab="Ploidy",ylab="Heterogeneity",type='l',lwd=2,tck=0.022)
    dev.off()
  }
  
}
